x-environment:
  &x-environment
  INITIAL: "${INITIAL:-0}"

services:
  web:
    command: sh -c 'while true; do ./manage.py runserver 0.0.0.0:8000; sleep 1; done'
    build:
      target: dev
    volumes:
      - .:/app/
      # - .venv:/venv/
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=pontsun'
      - 'traefik.http.middlewares.https_redirect.redirectscheme.scheme=https'
      - 'traefik.http.middlewares.https_redirect.redirectscheme.permanent=true'
      - 'traefik.http.routers.hello.rule=Host(`membership.docker.test`)'
      - 'traefik.http.routers.hello.middlewares=https_redirect'
      - 'traefik.http.routers.hello.service=web-django-hello'
    networks:
      - 'pontsun'
      - 'default'

networks:
    pontsun: {external: true}
