# Generated by Django 5.1.5 on 2025-04-25 14:28

from django.db import migrations
import phonenumbers
import phonenumber_field.modelfields


def convert_phones(apps, schema_editor):
    Member = apps.get_model("core", "Member")
    for member in Member.objects.all():
        if member.phone_old:
            phone = phonenumbers.parse(member.phone_old, region="CH")
            number = str(
                phonenumbers.format_number(phone, phonenumbers.PhoneNumberFormat.E164)
            )
            member.phone = number
            member.phone_old = None
            member.save()


def unconvert_phones(apps, schema_editor):
    Member = apps.get_model("core", "Member")
    for member in Member.objects.all():
        if member.phone:
            member.phone_old = member.phone
            member.save()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_invoice_unique_reference"),
    ]

    operations = [
        migrations.RenameField(
            model_name="member",
            old_name="phone",
            new_name="phone_old",
        ),
        migrations.AddField(
            model_name="member",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, null=True, region=None
            ),
        ),
        migrations.RunPython(
            code=convert_phones,
            reverse_code=unconvert_phones,
        ),
        migrations.RemoveField(
            model_name="member",
            name="phone_old",
        ),
    ]
