# Generated by Django 6.0.6 on 2026-06-18 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_rename_phone_member_phone_old"),
    ]

    operations = [
        migrations.CreateModel(
            name="CamtImport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="uploads/camt/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="camt_imports",
                        to="core.subscription",
                    ),
                ),
            ],
            options={
                "db_table": "camt_import",
                "ordering": ["-created_at"],
            },
        ),
    ]
