# Generated by Django 6.0.6 on 2026-06-18 22:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_camtimport"),
    ]

    operations = [
        migrations.AlterField(
            model_name="camtimport",
            name="file",
            field=models.FileField(
                upload_to="uploads/camt/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["xml"]
                    )
                ],
            ),
        ),
    ]
