# Generated by Django 5.1.5 on 2025-02-10 17:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_membersubscription_parent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="member",
            name="parent",
        ),
    ]
