# Generated by Django 5.1.5 on 2025-02-12 17:43

from django.db import migrations

from myapp.models.member_subscription import MemberSubscription


def calculate_price(apps, schema_editor):
    for sub in MemberSubscription.objects.all():
        sub.price = sub.get_price()
        sub.save()


def remove_price(apps, schema_editor):
    for sub in MemberSubscription.objects.all():
        sub.price = None
        sub.save()


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0003_remove_member_parent"),
    ]

    operations = [
        migrations.RunPython(calculate_price, reverse_code=remove_price),
    ]
