# Generated by Django 5.1.5 on 2025-02-13 07:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0004_membersubscription_price"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.UniqueConstraint(
                fields=("reference",), name="unique_reference"
            ),
        ),
    ]
