name: CI

on:
  push:
    branches:
      - main
  pull_request: ~
  workflow_dispatch: ~

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build DEV Docker images
        uses: docker/bake-action@v6
        with:
          load: true
          files: |
            compose.yaml
            compose.dev.yaml
          set: |
            *.cache-from=type=gha,scope=${{github.ref}}
            *.cache-from=type=gha,scope=refs/heads/main
            *.cache-to=type=gha,scope=${{github.ref}},mode=max
  tests:
    name: test
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'
      - name: Install pip dev dependencies
        run: pip install -r requirements.dev.txt

      - name: Ruff format
        run: ruff format --check

      - name: Ruff check
        run: ruff check

      - name: Migrations and fixtures
        run: |
          ./manage.py migrate
          ./manage.py loaddata 1_member.json
          ./manage.py loaddata 2_subscription.json
          ./manage.py loaddata 3_member_subscription.json