name: CI

on:
  push:
  pull_request:

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:

  tests:
    name: Tests

    env:
      extensions: amqp,apcu,igbinary,intl,mbstring,memcached,redis

    strategy:
      matrix:
        include:
          - php: '8.1'
#          - php: '8.2'
            #mode: experimental
      fail-fast: false

    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          coverage: "none"
          ini-values: date.timezone=UTC,memory_limit=-1,default_socket_timeout=10,session.gc_probability=0,apc.enable_cli=1,zend.assertions=1
          php-version: "${{ matrix.php }}"
          extensions: "${{ env.extensions }}"
          tools: composer:v2, php-cs, phpunit, phpstan

      - name: Configure environment
        run: |
          git config --global user.email ""
          git config --global user.name "CI"
          git config --global init.defaultBranch main
          git config --global advice.detachedHead false

          COMPOSER_HOME="$(composer config home)"
# echo COMPOSER_UP='composer update --no-progress --ansi'$([[ "${{ matrix.php }}" = "8.2" ]] && echo ' --ignore-platform-req=php+') >> $GITHUB_ENV
      - name: Install dependencies
        run: |
          echo "::group::composer update"
          composer install
          echo "::endgroup::"

      - name: Run phpunit
        run: |
            composer run-script db-create-test
            composer phpunit

      - name: Run phpstan
        run: composer phpstan

      - name: Run phpcs
        run: composer phpcs
